analyzer/urls.py
from django.conf.urls import url

from analyzer.views import IndexView

app_name = 'analyzer'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^analyze/$', IndexView.scrape, name='analyze'),
    url(r'^reports/$', IndexView.reports, name='reports'),
    url(r'^newspec/$', IndexView.analyse_newspec, name='newspec')
]

emotion_analysis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('analyzer.urls'))
]

analyzer/models.py
from __future__ import print_function
from __future__ import print_function
from __future__ import print_function
from __future__ import unicode_literals

import json
import os.path
import pickle
import subprocess

import collections
from django.db import models
from nltk.corpus import movie_reviews as reviews

from analyzer.build import build_and_evaluate


class Amazon_Scrape(models.Model):
    amazon_url = models.URLField(max_length=100)

    def fun(self, url):
        # Define command and arguments
        command = 'python'

        path = os.getcwd()

        path2script = path + '/parsers/parse_amazon.py'

        # Variable number of args in a list
        args = [url]

        # Build subprocess command
        cmd = [command, path2script] + args
        # check_output will run the command and store to result
        x = subprocess.call(cmd, universal_newlines=True)


class Amazon_Analyse(models.Model):
    def analyse_class(self):

        model = self.get_model()
        # print(show_most_informative_features(model,'this is a nice day',n=50))
        # print(show_most_informative_features(model,'this is a worst day',n=50))
        comments, ratings = self.parse_data()
        comments_sentiment = model.predict(comments)
        # print(comments_sentiment)

        specs = ['camera', 'performance', 'battery', 'look', 'feel', 'money', 'sound', 'network', 'storage', 'software']
        # specs = []
        total_score = []
        data = []
        comments_list = collections.defaultdict(lambda: [])
        self.generate_specification_sentiment(comments, comments_list, comments_sentiment, data, ratings,
                                              specs, total_score)

        net_score = round(sum(total_score) / len(total_score), 2)
        # net_score = 0
        print("total score", net_score)

        return net_score, data, comments_list, comments_sentiment

    def get_model(self):
        path = os.getcwd()
        filename = path + '/dump.pkl'
        if os.path.isfile(filename):
            with open(filename, 'rb') as f:
                model = pickle.load(f)
        else:
            X = [reviews.raw(fileid) for fileid in reviews.fileids()]
            y = [reviews.categories(fileid)[0] for fileid in reviews.fileids()]
            model = build_and_evaluate(X, y, outpath=filename)

        return model

    def generate_specification_sentiment(self, comments, comments_list, comments_sentiment, data, ratings,
                                         specs, total_score):

        save_path = os.getcwd() + '/data/'
        global emotion
        for spec in specs:
            spec_comments = []

            for i, comment in enumerate(comments):
                if spec in comment.split():
                    emotion = comments_sentiment[i]

                    spec_comments.append([comment, ratings[i], emotion])
                    comments_list[spec].append([int(emotion), comment])

            comments_list[spec].sort()

            if len(spec_comments) > 0:
                sentiment_value = self.calculate_sentiment(spec, spec_comments, total_score)
                data.append((spec, sentiment_value))

            completeFileName = os.path.join(save_path, spec + ".txt")

            with open(completeFileName, 'wb') as fp:
                pickle.dump(spec_comments, fp)

    def calculate_sentiment(self, spec, spec_comments, total_score):
        sentiment_value = sum(i[2] for i in spec_comments) * 1.0 / len(spec_comments)
        sentiment_value = round(sentiment_value, 3) * 10
        total_score.append(sentiment_value)
        sentiment_value = round(sentiment_value, 3)
        print(spec, sentiment_value)
        return sentiment_value

    def Amazon_spec(self, tokenn):

        comments, ratings = self.parse_data()

        model = self.get_model()

        comments_sentiment = model.predict(comments)

        print(comments_sentiment)
        specs = [tokenn]

        total_score = []
        data = []
        comments_list = collections.defaultdict(lambda: [])
        self.generate_specification_sentiment(comments, comments_list, comments_sentiment, data, ratings,
                                              specs, total_score)
        if len(data) == 0:
            return [], comments_list
        else:
            return data[0][1], comments_list

    def parse_data(self):
        with open('amazon_data.json') as data_file:
            data = json.load(data_file)
        comments = [data["reviews"][i]["review_text"] for i in range(len(data["reviews"]))]
        ratings = [data["reviews"][i]["review_rating"] for i in range(len(data["reviews"]))]
        return comments, ratings

analyzer/forms.py
from django import forms


class ScrapeForm(forms.Form):
    url = forms.URLField(label='Url of product', max_length=1000)


class NewSpec(forms.Form):
    spec = forms.CharField(label='', max_length=1000)

analyzer/views.py
import json
import os

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from analyzer.forms import ScrapeForm, NewSpec
from analyzer.models import Amazon_Scrape, Amazon_Analyse


class IndexView(View):
    http_method_names = [u'get', u'post']

    def get(self, request):
        form = ScrapeForm()
        return render(request, 'index.html', {'form': form})

    @csrf_exempt
    def scrape(request):
        # create a form instance and populate it with data from the request:
        form = ScrapeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # name_obj = Amazon_Url.objects.create(url=form.cleaned_data['url'] )
            url = form.cleaned_data['url']
            print('Url is received')
            q = Amazon_Scrape()
            q.fun(url)
            print('Url is', url)

            return HttpResponseRedirect('/reports')

        product_url = request.POST.get('search_query', "")
        print("-------------" + product_url + "---------------")
        return HttpResponse("<h1>Error occurred while analyzing : " + product_url + "</h1>")

    def reports(request):
        print("analyse : get function")
        q = Amazon_Analyse()
        score, data, comments, comments_sentiment = q.analyse_class()

        with open('amazon_data.json') as data_file:
            f = json.load(data_file)

        title = f['name']

        # getting image data
        imageFile = open(os.getcwd() + "/imageData.txt", "r")
        base64 = imageFile.read()

        form = NewSpec()
        specs_list = []
        p = []
        f = open('specs.txt')
        for line in f:
            p.append(line)
        # print p
        try:
            for i in range(0, len(p), 2):
                specs_list.append((p[i], p[i + 1]))

            print(specs_list)
        except Exception:
            specs_list = []
            form = ""

        positive = 0
        negative = 0
        for i, emotion in enumerate(comments_sentiment):
            if emotion == 1:
                positive += 1
            else:
                negative += 1

        return render(request, 'result.html',
                      {'data': data,
                       'comments': dict(comments),
                       'title': title,
                       'image': base64,
                       'form': form,
                       'specs_list': specs_list,
                       'total_reviews': positive + negative,
                       'score': score,
                       'positive_sentiment': positive,
                       'negative_sentiment': negative,
                       }
                      )

    def analyse_newspec(request):
        if request.method == 'POST' and request.is_ajax:
            form = NewSpec(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # name_obj = Amazon_Url.objects.create(url=form.cleaned_data['url'] )
            spec = form.cleaned_data['spec']
            print(spec)
            qq = Amazon_Analyse()
            value, comments = qq.Amazon_spec(spec)
            # print 'Url is', url
            print('value is', value)
            print(comments)

            data = json.dumps({
                'heading': spec,
                'value': value,
                'comments_spec': comments,
            })
            return JsonResponse(data, safe=False)
        print('not sent')

analyzer/templates/datanew.html
<form action="{% url 'analyzer:scrape' %}" method="POST">
    {% csrf_token %}


    {{ form }}

    <button type="button">Submit</button>

</form>

analyzer/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Emotion Analysis</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
    <link rel="stylesheet" href="{% static 'css/bmn.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
</head>

<body>

<!-- Preloader -->
{% comment %}
<div id="preloader">
    <div id="status"></div>
</div>
{% endcomment %}

<div id="page">
    <header>
        <div class="inner">

        </div>
        <!-- NavBar-->
        <nav class="navbar-default" role="navigation" style="margin-left: 100px; margin-right: 80px">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#home" style="color: #fff; font-size: xx-large; font-weight: bold">Emotion
                    Analysis</a>
            </div>

            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    {#<li class="menuItem"><a href="#whatis">What is?</a></li>#}
                    <li class="menuItem"><a href="{% url 'analyzer:home' %}"
                                            style="color: #fff; font-size: medium; font-weight: bold">Scrape</a></li>
                    <li class="menuItem"><a href="{% url 'analyzer:reports' %}"
                                            style="color: #fff; font-size: medium ;font-weight: bold">Reports</a></li>
                </ul>

            </div>
        </nav>

    </header>
    <div id="content">
        <h1>Emotion Analysis: Comments Analysis Tool</h1>
        <p>Enter a website below to analyse the comments for the target product</p>
        <form class="search_form" action="{% url 'analyzer:analyze' %}" method="post" id="scrape">
            {% csrf_token %}

            <div class="form-group" id="search_query">
                {{ form }}
                <button id="search_button" type="submit"><span>Analyse</span></button>
            </div>
        </form>
        <div style="margin:100px;text-align: center">
            <img style="height:200px;width:200px;" src="{% static "images/loading.gif" %}" id="spinner">
        </div>
        <div style="margin-top:50px;"></div>
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</body>
</html>
{% comment %}
<div class="panel panel-default">
    <div class="panel-heading">
        Enter the URL of product to be analysed
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-offset-3">
                <form class="form-horizontal" action="/scrape/data/" method="post" id="scrape">
                    {% csrf_token %}

                    <div class="form-group">
                        {{ form }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary col-md-offset-1">Analyse</button>
                    </div>
                </form>
                <img src="{% static "Images/spinner.gif" %}" id="spinner">
            </div>
        </div>
    </div>
</div>{% endcomment %}

<script>

    $(document).ready(function () {
        $("#spinner").hide()
    });

    $("#scrape").submit(function (event) {
        $("#spinner").show()
    });
</script>

analyzer/templates/result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/new.css' %}"/>

</head>
<body style="background-color: #F9F9F9;">
<div>
    <h1>FIXED NAVBAR</h1>
</div>
<nav class="row navbar navbar-inverse navbar-fixed-top" id="cen">
    <div class="navbar-header col-md-10">
        <h1>{{ title }}</h1>
    </div>
    <div class="col-md-2 " style="text-align: center"><a style="color: white; text-decoration: none;" href="/"><h1>
        Back</h1></a></div>
</nav>

<br>
<div class="container">
    <div class="row" style="margin-top: 20px">
        <div class="col-md-4" id="image" style="text-align: center;">

            <img id="product-image" src="" alt="image"
                 style="background-color: #F9F9F9;"/>
        </div>
        <div class="col-md-4">
            <canvas id="top_chart" width="450px" height="350px"></canvas>

        </div>
        <div class="col-md-4" style="text-align: left; margin-top:60px">
            <h3>Emotion : {{ score }}/10</h3>
            <h3>Total reviews parsed : {{ total_reviews }}</h3>
            <h3>Positive reviews : {{ positive_sentiment }}</h3>
            <h3>Negative reviews : {{ negative_sentiment }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tbody>
                {% for s1,s2 in specs_list %}
                    <tr class="success">
                        <td class="label1" style="background-color: rgba(255,255,255,.15);"> {{ s1 }} </td>
                        <td class="value" style="background-color: rgba(255,255,255,.15);">{{ s2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

<br>
<div class="col-md-offset-1">

    <form class="form-inline" id="custom-spec" action="{% url 'analyzer:newspec' %}" method="post">
        {% csrf_token %}
        <label>Enter your own specification</label>
        <div class="form-group">
            {{ form }}
        </div>
        <div class="form-group">
            <button type="submit" id="custom-spec-btn" class="btn btn-primary col-md-offset-1">Search</button>
        </div>
        <br>
        <br>
    </form>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4" id='radio-home'>

            {% for spec,sent in data %}
                <label><input type="radio" name="feature" value={{ sent }} id={{ spec }}> {{ spec }} {{ sent }}</label>
                <hr>
            {% endfor %}

        </div>
        <div class="col-md-8">
            <div class="chart">
                <div><h1 id="heading">Select any item </h1></div>

                <hr>
                <canvas id="chart" width="500" height="200px"></canvas>
            </div>
        </div>
    </div>
    <div>
        <br><br>
        <div class="comments positive">
            <h3 id="pos"></h3>
            <hr/>
            <ul id="positive-comments">
                <!-- javascript prints comments here by parsing Jcomments_list obj -->
            </ul>
        </div>
        <br>
        <div class="comments negative">
            <h3 id="neg"></h3>
            <hr/>
            <ul id="negative-comments">
                <!-- javascript prints comments here by parsing Jcomments_list obj -->
            </ul>
        </div>
        <br>
    </div>
</div>


<script>

    //when documnet is completely loaded load this scripts
    $(document).ready(function () {

        radioButtonClickListener();
        displayImage();
        formSubmitListener();

        positive = {{ positive_sentiment }};
        total = {{ total_reviews }};
        sentiment = (positive / total) * 10;

        displayChart(Math.round(sentiment, 2), $("#top_chart"));
    });

    var comments_list = {{comments|safe}};
    //global variables
    var myChart;

    function radioButtonClickListener() {

        $('input[type=radio][name=feature]').change(function () {

            var heading = $(this).attr("id");
            var value = $(this).val();

            //set chart heading
            $("#heading").text(heading);

            //load chart
            displayChart(value, $("#chart"));
            displayComments(heading);
        });
    }

    function displayChart(value, ctx) {

        //destroy existing chart if any and load new chart
        if (myChart != null) {

            myChart.destroy();
        }

        //creation of new chart

        var labels = [
            "Positive",
            "Negative"
        ]

        var backgroundColor = [
            "#5cd65c",
            "#ff4d4d"
        ]
        var hoverBackgroundColor = [
            "#2eb82e",
            "#ff1a1a"
        ]
        var data = [value, (10.0 - value).toFixed(1)]

        if (value == 0) {
            data = [10]
            labels = ["No data"]
            backgroundColor = ["#78909C"]
            hoverBackgroundColor = ["#546E7A"]
        }

        myChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: labels,
                datasets: [
                    {
                        data: data,
                        backgroundColor: backgroundColor,
                        hoverBackgroundColor: hoverBackgroundColor
                    }]
            }
        });
    }
    function displayComments(heading) {

        for (var key in comments_list) {
            if (comments_list.hasOwnProperty(key)) {
                if (key === heading) {
                    console.log(comments_list[key]);
                    var comments = comments_list[key];
                    //where to append lists
                    $("#pos").text("Positive Comments");
                    $("#neg").text("Negative Comments");

                    var positiveComments = $('#positive-comments')
                    positiveComments.html("");

                    var negativeComments = $('#negative-comments')
                    negativeComments.html("");

                    //appending loop
                    for (var i = 0; i < comments.length; i++) {
                        console.log(comments)
                        var sentiment = comments[i][0]
                        if (sentiment === 0) {
                            $('<li/>')
                                .text(comments[i][1])
                                .appendTo(negativeComments);
                        }
                        else if (sentiment === 1) {
                            $('<li/>')
                                .text(comments[i][1])
                                .appendTo(positiveComments);
                        }
                    }
                }
            }
        }
    }

    function displayImage() {

        var image = {{image|safe}};

        $("#product-image").attr("src", image);
    }


    function formSubmitListener() {

        $("#custom-spec").on("submit", function (e) {

            e.preventDefault();

            var url = "/newspec/";

            $.ajax({
                type: 'POST',
                url: url,
                data: new FormData($(this)[0]),
                /* data : $(this).serialize(), */
                /* enctype : 'multipart/form-data', */
                /* encoding : 'multipart/form-data', */
                cache: false,
                processData: false,
                contentType: false,
                beforeSend: function () {
                    $("#custom-spec-btn").prop('disabled', true);
                },
                success: function (response) {
                    response = JSON.parse(response);
                    var heading = response.heading;
                    var comments_spec = response.comments_spec;

                    comments_list[heading] = comments_spec[heading];

                    var label = document.createElement("label");
                    var radio = document.createElement("input");
                    radio.type = "radio";
                    radio.name = "feature";
                    radio.value = response.value;
                    radio.id = response.heading;

                    label.appendChild(radio);
                    radio_home = document.getElementById("radio-home");
                    text = ' ' + heading;
                    label.appendChild(document.createTextNode(text));
                    radio_home.appendChild(label);
                    $("#heading").text(heading);
                    displayChart(response.value, $("#chart"));
                    displayComments(heading)

                    var hrtag = "<hr/>";
                    $(label).after(hrtag);

                    $("#custom-spec-btn").prop('disabled', false);
                    radioButtonClickListener();


                },
                error: function (XMLHttpRequest,
                                 textStatus, errorThrown) {
                    /* console.info("Status: " + XMLHttpRequest);
                     alert("Status: " + textStatus);
                     alert("Error: " + errorThrown); */
                    alert("Error occured, try again.")
                    $("#custom-spec-btn").prop('disabled', false);
                }
            });

        });
    }


</script>
<style type="text/css">
    .comments.negative {
        border: 1px solid #e9e9e9;
        background-color: #DE5252;
        color: antiquewhite;
        border-radius: 25px;
        padding-bottom: 25px;
    }
</style>
</body>
</html>